[package]
name = "tenebra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
axum = "0.7.5"
axum-macros = "0.4.1"
base64 = "0.22.0"
enigo = "0.2.0"
lazy_static = "1.4.0"
nix = { version = "0.28.0", features = ["signal"] }
serde = "1.0.197"
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features =  [ "cors" ] }
webrtc = "0.10.1"
