[package]
name = "tenebra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
askama = "0.12.1"
axum = "0.7.5"
axum-macros = "0.4.1"
base64 = "0.22.0"
bytecodec = "0.4.15"
enigo = { git = "https://github.com/UE2020/enigo.git", branch = "main" }
gstreamer = "0.23.0"
gstreamer-app = "0.23.0"
igd-next = { version = "0.14.3", features = ["aio_tokio"] }
local-ip-address = "0.6.1"
rand = "0.8.5"
serde = "1.0.197"
serde_json = "1.0.115"
str0m = { version = "0.6.2" }
stun_codec = "0.3.5"
sysinfo = "0.31.3"
tokio = { version = "1.39.3", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }
shalloc = "0.1.0"
axum-server = { version = "0.7.1", features = ["tls-rustls"] }

[build-dependencies]
cc = "1.1.14"
bindgen = "0.69.4"

[features]
default = []
vaapi = []
upnp = []
ice-tcp = []
