[package]
name = "tenebra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
askama = "0.12.1"
async-trait = "0.1.80"
axum = "0.7.5"
axum-macros = "0.4.1"
base64 = "0.22.0"
bytecodec = "0.4.15"
enigo = "0.2.1"
gstreamer = "0.22.6"
gstreamer-app = "0.22.6"
local-ip-address = "0.6.1"
rand = "0.8.5"
serde = "1.0.197"
serde_json = "1.0.115"
str0m = { version = "0.6.1" }
stun_codec = "0.3.5"
sysinfo = "0.30.13"
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors"] }
