[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

[dist.dependencies.apt]
"libgstreamer1.0-dev" = "*"
"libgstreamer-plugins-base1.0-dev" = "*"
"libgstreamer-plugins-bad1.0-dev" = "*"
"gstreamer1.0-plugins-base" = "*"
"gstreamer1.0-plugins-good" = "*"
"gstreamer1.0-plugins-bad" = "*"
"gstreamer1.0-plugins-ugly" = "*"
"gstreamer1.0-libav" = "*"
"gstreamer1.0-tools" = "*"
"gstreamer1.0-x" = "*"
"gstreamer1.0-alsa" = "*"
"gstreamer1.0-gl" = "*"
"gstreamer1.0-gtk3" = "*"
"gstreamer1.0-qt5" = "*"
"gstreamer1.0-pulseaudio" = "*"

[dist.github-custom-runners]
x86_64-unknown-linux-gnu = "ubuntu-latest"
