target_bitrate = 4000
startx = 0
starty = 0
port = 8080
password = "placeholder"
sound_forwarding = true  # Linux only: other platforms will behave as if this is always false
hwencode = false         # Linux and macOS only: other platforms will behave as if this is always false
vapostproc = false       # Linux only: other platforms will behave as if this is always false
no_bwe = false
full_chroma = false      # full_chroma cannot be used in combination with hwencode
tcp_upnp = true
vbv_buf_capacity = 120   # Not required, default is 120
cert = "/path/to/cert"
key = "/path/to/key"
